# Generated by Django 6.1.2 on 2026-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending ⏳'), ('Approved', 'Approved ✅'), ('Rejected', 'Rejected ❌')], default='Pending', max_length=20),
        ),
    ]
